name: code_management
description: Code Management

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  dio: ^4.0.4
  retrofit: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.2.0-beta-1
  cached_network_image: ^3.2.0
  drift: ^1.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1
  drift_dev: ^1.3.0

flutter:
  uses-material-design: true
